// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEF9cpCn1jOd2_S22W4XuHg4azfVvBqnY',
    appId: '1:384240808585:web:4771eabe0519d27095cc58',
    messagingSenderId: '384240808585',
    projectId: 'smart-shopping-chamo-9bb59',
    authDomain: 'smart-shopping-chamo-9bb59.firebaseapp.com',
    storageBucket: 'smart-shopping-chamo-9bb59.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBAtbxcVo4O15t6iKh_oQdxGfr3nSbQZ4',
    appId: '1:384240808585:android:71736aef09c7f16a95cc58',
    messagingSenderId: '384240808585',
    projectId: 'smart-shopping-chamo-9bb59',
    storageBucket: 'smart-shopping-chamo-9bb59.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTqrkL6zpFkzBn996_K559CNNbnAq_afQ',
    appId: '1:384240808585:ios:d9bdd5d2974d4e5e95cc58',
    messagingSenderId: '384240808585',
    projectId: 'smart-shopping-chamo-9bb59',
    storageBucket: 'smart-shopping-chamo-9bb59.firebasestorage.app',
    iosBundleId: 'com.example.smartShopping',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTqrkL6zpFkzBn996_K559CNNbnAq_afQ',
    appId: '1:384240808585:ios:d9bdd5d2974d4e5e95cc58',
    messagingSenderId: '384240808585',
    projectId: 'smart-shopping-chamo-9bb59',
    storageBucket: 'smart-shopping-chamo-9bb59.firebasestorage.app',
    iosBundleId: 'com.example.smartShopping',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEF9cpCn1jOd2_S22W4XuHg4azfVvBqnY',
    appId: '1:384240808585:web:b62af9b82b39ad8395cc58',
    messagingSenderId: '384240808585',
    projectId: 'smart-shopping-chamo-9bb59',
    authDomain: 'smart-shopping-chamo-9bb59.firebaseapp.com',
    storageBucket: 'smart-shopping-chamo-9bb59.firebasestorage.app',
  );
}
